### ISSUE TITLE
Discriminated union converter fails

### ISSUE THREAD

**Issue by endeavour** [haf/Newtonsoft.Json.FSharp#1]
```
type Msg =
| Bla
| Ping of fooId:int64
```

Trying to serialize then deserialize an instance of Bla throws an exception:

```
> Newtonsoft.Json.JsonReaderException: Invalid token '"_Bla"', at path 'Bla'
>    at Newtonsoft.Json.FSharp.SerialisationFunctions.fail[a,b](JsonReader reader, a token)
   at Newtonsoft.Json.FSharp.SerialisationFunctions.readProp@23.Invoke(Object v)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at <StartupCode$Newtonsoft-Json-FSharp>.$UnionConverter.ReadJson@52-13.Invoke(JsonReader reader, String n)
   at Newtonsoft.Json.FSharp.UnionConverter.ReadJson(JsonReader reader, Type t, Object _arg1, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at FSI_0030.deserialize(Type t, Byte[] data) in C:\dev\fsharp\Serialization.fs:line 53
   at <StartupCode$FSI_0034>.$FSI_0034.main@()
Stopped due to error
```

**Comment by haf** [comment]
Hi there. Recommend moving to Chiron https://github.com/SuaveIO/suave/blob/master/examples/JsonApi/Program.fs

**Comment by endeavour** [comment]
It seems Newtonsoft Json now supports DUs natively so this package now seems redundant
